# Generated by Django 4.1.7 on 2023-07-24 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockComponents',
            fields=[
                ('art_number', models.IntegerField(help_text='Аритикул - соответсвует артикулу в файле склада.', primary_key=True, serialize=False)),
                ('component_stock_naming', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('subtype', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
