# Generated by Django 4.1.7 on 2023-08-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFromExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_number', models.IntegerField(blank=True, help_text='Поле - Аритикул - в файле склада.', null=True, verbose_name='Артикул')),
                ('category', models.CharField(blank=True, help_text='Поле - Тип - в файле склада.', max_length=250, null=True, verbose_name='Тип')),
                ('type', models.CharField(blank=True, help_text='Поле - Вид - в файле склада.', max_length=250, null=True, verbose_name='Вид')),
                ('subtype', models.CharField(blank=True, help_text='Поле - Подвид - в файле склада.', max_length=250, null=True, verbose_name='Подвид')),
                ('component_stock_naming', models.CharField(blank=True, help_text='Поле - Название (Комплектующие склада) - в файле склада.', max_length=250, null=True, verbose_name='Название\n(Комплектующие склада)')),
                ('corpus_din', models.CharField(blank=True, help_text='Поле - Корпус DIN (для механики) - в файле склада.', max_length=250, null=True, verbose_name='Корпус DIN (для механики)')),
                ('quantity_in_stock', models.CharField(blank=True, help_text='Поле - Склад основной - в файле склада.', max_length=250, null=True, verbose_name='Склад основной')),
                ('available_for_issue', models.CharField(blank=True, help_text='Поле - Доступно к выдаче - в файле склада.', max_length=250, null=True, verbose_name='Доступно\nк выдаче')),
                ('price', models.CharField(blank=True, help_text='Поле - Цена, $ - в файле склада.', max_length=250, null=True, verbose_name='Цена, $')),
                ('part_number_1', models.CharField(blank=True, help_text='Поле - PART Number - в файле склада.', max_length=250, null=True, verbose_name='PART Number')),
                ('manufacturer_1', models.CharField(blank=True, help_text='Поле - Производитель - в файле склада.', max_length=250, null=True, verbose_name='Производитель')),
                ('part_number_2', models.CharField(blank=True, help_text='Поле - Part number #2 - в файле склада.', max_length=250, null=True, verbose_name='Part number #2')),
                ('manufacturer_2', models.CharField(blank=True, help_text='Поле - Производитель #2 - в файле склада.', max_length=250, null=True, verbose_name='Производитель #2')),
            ],
        ),
        migrations.AlterField(
            model_name='stockcomponents',
            name='art_number',
            field=models.IntegerField(help_text='Поле - Аритикул - в файле склада.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockcomponents',
            name='category',
            field=models.CharField(blank=True, help_text='Поле - Тип - в файле склада.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stockcomponents',
            name='component_stock_naming',
            field=models.CharField(blank=True, help_text='Поле - Название (Комплектующие склада) - в файле склада.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stockcomponents',
            name='subtype',
            field=models.CharField(blank=True, help_text='Поле - Подвид - в файле склада.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stockcomponents',
            name='type',
            field=models.CharField(blank=True, help_text='Поле - Вид - в файле склада.', max_length=250, null=True),
        ),
    ]
