# Generated by Django 4.1.7 on 2023-08-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0002_stockfromexcel_alter_stockcomponents_art_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfromexcel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
