# Generated by Django 4.1.7 on 2023-08-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0003_stockfromexcel_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfromexcel',
            name='corpus_din',
            field=models.CharField(blank=True, help_text='Поле - Корпус DIN (для механики) - в файле склада.', max_length=250, null=True, verbose_name='        Корпус                    DIN (для механики)'),
        ),
    ]
