# Generated by Django 4.1.7 on 2023-08-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0004_alter_stockfromexcel_corpus_din'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfromexcel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
