# Generated by Django 4.1.7 on 2023-08-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0007_alter_stockfromexcel_art_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfromexcel',
            name='available_for_issue',
            field=models.CharField(blank=True, default='', help_text='Поле - Доступно к выдаче - в файле склада.', max_length=250, null=True, verbose_name='Доступно\nк выдаче'),
        ),
        migrations.AlterField(
            model_name='stockfromexcel',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Поле - Тип - в файле склада.', max_length=250, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='stockfromexcel',
            name='component_stock_naming',
            field=models.CharField(blank=True, default='', help_text='Поле - Название (Комплектующие склада) - в файле склада.', max_length=250, null=True, verbose_name='Название\n(Комплектующие склада)'),
        ),
        migrations.AlterField(
            model_name='stockfromexcel',
            name='corpus_din',
            field=models.CharField(blank=True, default='', help_text='Поле - Корпус DIN (для механики) - в файле склада.', max_length=250, null=True, verbose_name='        Корпус                    DIN (для механики)'),
        ),
        migrations.AlterField(
            model_name='stockfromexcel',
            name='manufacturer_1',
            field=models.CharField(blank=True, default='', help_text='Поле - Производитель - в файле склада.', max_length=250, null=True, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='stockfromexcel',
            name='manufacturer_2',
            field=models.CharField(blank=True, default='', help_text='Поле - Производитель #2 - в файле склада.', max_length=250, null=True, verbose_name='Производитель #2'),
        ),
        migrations.AlterField(
            model_name='stockfromexcel',
            name='part_number_1',
            field=models.CharField(blank=True, default='', help_text='Поле - PART Number - в файле склада.', max_length=250, null=True, verbose_name='PART Number'),
        ),
        migrations.AlterField(
            model_name='stockfromexcel',
            name='part_number_2',
            field=models.CharField(blank=True, default='', help_text='Поле - Part number #2 - в файле склада.', max_length=250, null=True, verbose_name='Part number #2'),
        ),
        migrations.AlterField(
            model_name='stockfromexcel',
            name='price',
            field=models.CharField(blank=True, default='', help_text='Поле - Цена, $ - в файле склада.', max_length=250, null=True, verbose_name='Цена, $'),
        ),
        migrations.AlterField(
            model_name='stockfromexcel',
            name='quantity_in_stock',
            field=models.CharField(blank=True, default='', help_text='Поле - Склад основной - в файле склада.', max_length=250, null=True, verbose_name='Склад основной'),
        ),
        migrations.AlterField(
            model_name='stockfromexcel',
            name='subtype',
            field=models.CharField(blank=True, default='', help_text='Поле - Подвид - в файле склада.', max_length=250, null=True, verbose_name='Подвид'),
        ),
        migrations.AlterField(
            model_name='stockfromexcel',
            name='type',
            field=models.CharField(blank=True, default='', help_text='Поле - Вид - в файле склада.', max_length=250, null=True, verbose_name='Вид'),
        ),
    ]
