# Generated by Django 4.1.7 on 2023-09-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0008_alter_stockfromexcel_available_for_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfromexcel',
            name='weight_g',
            field=models.CharField(blank=True, default='', help_text='Поле - Вес, г - в файле склада.', max_length=250, null=True, verbose_name='Вес, г'),
        ),
    ]
