# Generated by Django 4.1.7 on 2023-09-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0009_stockfromexcel_weight_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfromexcel',
            name='comments_to_field_quantity_in_stock',
            field=models.TextField(blank=True, default='', help_text='КОММЕНТАРИЙ к полю - Склад основной - в файле склада.', null=True),
        ),
    ]
